name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Change this to your default branch if it's not 'main'
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    if: github.ref == 'refs/heads/main'  # Only run on push to main branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'  # Use the latest LTS version
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Build
        run: |
          echo "GITHUB_PAGES=true" >> $GITHUB_ENV
          npm run build
        env:
          GITHUB_PAGES: 'true'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
          single-commit: true
          commit-message: 'Deploy: 🚀 Deploy site'
          token: ${{ secrets.GITHUB_TOKEN }}
